import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ExternalLink } from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="min-h-screen flex flex-col bg-gradient-to-b from-slate-50 to-white text-slate-800">
              {/* Navbar */}
              <header className="w-full px-8 py-5 flex justify-between items-center border-b border-slate-200 bg-white">
                <Link 
                  href="/" 
                  className="text-xl font-semibold tracking-tight hover:opacity-80 transition-opacity"
                >
                  TypeMaster
                </Link>

                <nav className="flex items-center space-x-8 text-sm font-medium">
                  <Link href="/" className="hover:text-blue-600 transition-colors">
                    Home
                  </Link>
                  <Link href="/typing-test" className="hover:text-blue-600 transition-colors">
                    Typing Test
                  </Link>
                </nav>
              </header>
        {children}
              {/* Footer */}
              <footer className="border-t border-slate-200 py-12 text-center bg-white">
                <div className="space-y-4">
                  
                  <p className="text-sm text-slate-500">
                    © {new Date().getFullYear()} TypeMaster
                  </p>

                  <p className="text-base text-slate-600">
                    Designed & Developed by{" "}
                    
                    <a
                      href="https://tanjimul-portfolio.vercel.app"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="relative inline-flex items-center gap-1 font-medium text-slate-800 group"
                    >
                      <span className="relative">
                        MD TANJIMUL ALAM
                        
                        {/* Animated underline */}
                        <span className="absolute left-0 -bottom-1 h-[2px] w-0 bg-slate-800 transition-all duration-300 group-hover:w-full"></span>
                      </span>

                      <ExternalLink
                        size={16}
                        className="opacity-70 group-hover:opacity-100 transition-opacity duration-300"
                      />
                    </a>

                  </p>

                  <p className="text-xs text-slate-400">
                    Made with ❤️
                  </p>

                </div>
              </footer>
              </main>
      </body>
    </html>
  );
}
